flowers <- read.csv(file="~/Desktop/cs\ 251/assign5/Q2/assign5_q2.csv")
cat("Mean of sepal Lengths: ",mean(flowers$Sepal.Length),"\n")
cat("Mean of sepal Widths : ",mean(flowers$Sepal.Width),"\n")
cat("Mean of petal Lengths: ",mean(flowers$Petal.Length),"\n")
cat("Mean of petal Widths : ",mean(flowers$Petal.Width),"\n")
cat("Contingency table: ")
table(flowers$Species,flowers$Good)
barplot(table(flowers$Species,flowers$Good))